---
title: "Nice Ride Machine Learning Outline"
author: '[Tony Tushar Jr](mailto:tonytusharjr@gmail.com)'
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  html_notebook:
    fig_caption: yes
    fig_height: 6
    toc: yes
    toc_depth: 4
    toc_float: no
  pdf_document:
    toc: yes
    toc_depth: '4'
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '2'
---

## How do you frame your main question as a machine learning problem? 

> The main question for this project is how does a given daily weather scenario affect the bike share use of casual and member riders? Framing this as a machine learning problem involves modeling the relationship between weather and bike riders via historical data in order to apply the modeling toward future weather scenarios in the next riding season.

## Is it a supervised or unsupervised problem? If it is supervised, is it a regression or a classification?

> We will begin under the premise that this problem is supervised and in the form of a regression, however, k means clustering might be applied preliminarily and regressions will be ran secondarily for each cluster determined. This would make the problem unsurpervised and then supervised.

## What are the main features (also called independent variables or predictors) that you'll use?

> There is a use for the geospatial variables in the data in order to first cluster stations that relate to a centroid geocoordinate. This features allows for the modeling of various station daily count densities rather than a general density per day. This would be a helpful feature in order to apply the solution for the problem toward maintenance tasks, bike rebalancing, and other operational objectives for Nice Ride MN. For this reason, there are two stages of modeling.

> For the first process of clustering, the important predictors are geospatial data points - latitude and longitude, clusters of bike share stations related to a centroid point, based on the distance properties gleaned from the geospatial coordinates.

> For the secondary phase of regression, the independent variables are the four main daily weather averages: 

> + Temperature
+ Wind Speed
+ Precipitation
+ Humidity

> Additionally there are other independent variables to consider:

> + Fog
+ Thunder
+ Hail

> There is likely to be multicollinearity between our independent variables, statistical tests can help assess this as the severity of interdependency amongst independent variables can diminish modeling ability.

## Which machine learning technique will you use?

> We will consider several independent weather variables following the linear form of a bike season and use the variables to estimate total daily bike use of casual and member riders. The model will fit the form of a linear regression, and a primary clustering component will also be required if the predicted daily bike volume is to be featured with daily variance by bike station cluster.

## How will you evaluate the success of your machine learning technique? What metric will you use?

> 60-75% of the data set, either the 2016 & 2017 seasons together or separately, will be utilized for training the model and the remaining percentage will be used to test the model. K means clustering requires an initial heuristic step of deciding on the number of clusters, however, various R packages provide for the exploration and suggestions when defining k. Adjusted R-squared will serve as a measurement of the accuracy and efficiency of the regression modeling.

## Additional things to consider:

> + Will need to settle on R packages for modeling and validating, updating this ML outline accordingly.
+ Training vs testing data split should be per month - perhaps 66% training and 33% testing.
+ Perhaps the casual and member data should be subset apart from one another and separate models built for each?
