---
title: "Nice Ride Stat Report"
author: "Tony Tushar Jr"
date: "February 2, 2018"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
```

----
```{r include=FALSE}
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```


This Exploratory Data Analysis (EDA) serves as a starting point for understanding our dataset prior regression and machine learning applications. A reminder of our two main questions and ultimate purpose of this project:

Two Main Questions:
- What is the affect of weather on bikeshare volume?
- How does the affect of weather on bikeshare volume differ between member and casual account types?

Ultimate Purpose:
- To provide a predictive model for weekly bikeshare volume based on the input of weather forecast variables.

In this EDA we will perform the following steps:

1. General exploration of dataset:
- What is the distribution of trips per month, by year?
- What is the distribution of trips per day of the week, by account type?
- What is the distibution of trips by weekday and weekend for the season, by year, by account type?
- Summary of trip distance in miles
- Summary of trip duration in minutes
- Are there outliers to address? If so, how are they to be addressed?

2. Pearson's product-moment correlations for the affects of primary weather variables on bikeshare volume:
- Affect of average temperature
- Affect of average wind speed
- Affect of precipitation
- Affect of relative humidity
- Affect of heat index

3. T-tests for primary weather variables and relationship to bike count by account type, member and casual:

4. Conclusions, next steps:

#Load packages
```{r}
library(tidyverse)
library(readr)
library(ggthemes)
library(lubridate)
```

#Load dataset
```{r}
Rides1617 <- read_csv("Nice_Ride_1617.csv")
View(Rides1617)
```

#1. General exploration of dataset:

##- What is the distribution of trips per month, for 2016-2017 seasons?
```{r}
#Create data subset
Trips_Month <- Rides1617 %>% count(Start_Year, Start_Month) %>% mutate(Percent_Year = prop.table(n))
head(Trips_Month, n=12)

#Setup plot properties for possible reuse
gg_prop_Month <- ggplot(data = data.frame(), aes(x = Start_Month, y = Percent_Year, fill = factor(Start_Year))) + 
  geom_bar(stat = 'identity', position = 'dodge', alpha = 2/3) + labs(x = "Start Month", y = "Percentage", title="Trip Distribution by Month, 2016-2017", subtitle="Heavy road construction in 2016, possible cause of trip volume differences for July and September")

#Plot data
gg_prop_Month %+% Trips_Month 
```
Trip distrubution is fairly even for a year-over-year comparison, however, July and September show larger variation. Research shows that 2016 was a particularly dense season of road construction, as Minneapolis installed biking lanes throughout the metro. This factor is likely a contributor to the variance between 2016 and 2017, however, we cannot control for construction data other than to note here.

##- What is the distribution of trips per day of the week, by account type?
```{r}
#Reorder days of the week
Rides1617$Start_DoWeek <- ordered(Rides1617$Start_DoWeek, levels=c("Sun", "Mon", "Tue", "Wed", "Thu", 
"Fri", "Sat"))

#Create data subset
Trips_Week <- Rides1617 %>% count(Start_Year, Start_DoWeek, Account_Type) %>% mutate(Percent_Year = prop.table(n))
head(Trips_Week, n=12)

#Setup plot properties for possible reuse
gg_prop_Week <- ggplot(data = data.frame(), aes(x = Start_DoWeek, y = Percent_Year, fill = factor(Account_Type))) + 
  geom_bar(stat = 'identity', position = 'dodge', alpha = 2/3) + facet_grid(Start_Year ~ .) + labs(x = "Day of the Week", y = "Percentage", title="Trip Distribution by Day and Account Type, 2016-2017", subtitle="Distribution for casual and member account types are inverse of each other", fill="Account Type")

#Plot data
gg_prop_Week %+% Trips_Week 
```
Daily distribution by year confirms consistency year-over-year, member riders are utilizing bikshare for commuting purposes while casual riders utilize bikeshare for leisure.

##- What is the distibution of trips per year by account type?
```{r}
#Create data subset
Trips_Account <- Rides1617 %>% count(Start_Year, Start_Month, Start_Day, Weekend, Account_Type) 
Trips_Account16 <- Trips_Account %>% mutate(Dates = as.Date(paste(Start_Year, Start_Month, Start_Day, sep='-'))) %>% filter(Start_Year==2016) 
Trips_Account17 <- Trips_Account %>% mutate(Dates = as.Date(paste(Start_Year, Start_Month, Start_Day, sep='-'))) %>% filter(Start_Year==2017) 

#Setup plot properties for possible reuse
gg_prop_Account <- ggplot(data = data.frame(), aes(x = Dates, y = n, color=factor(Account_Type))) + 
  geom_point(size=3, alpha = 2/3) + geom_jitter() + labs(x = "Date", y = "Total Rides", title="Trip Distribution by Weekday and Weekend", subtitle="", color="Account Type")

#Plot data
multiplot(gg_prop_Account %+% Trips_Account16, gg_prop_Account %+% Trips_Account17)
```

##- Summary of trip distance
```{r}
summary(Rides1617$Trip_DistanceMiles)
```
Median trip distance is 1.944 miles while the max is 29 miles, is this logical in comparison to trip duration?

##- Summary of trip duration in minutes
```{r}
summary(Rides1617$Total_DurationMin)  
```
It is odd to see a max ride observation of over 280,000 minutes, this equates to 194 days! How many bike rides are greater than one day?

##- Are there outliers to address? If so, how are they to be addressed?
```{r}
# What percentage of bike rides are over one day in length?
# Trips equal to or less than one day
Rides_Day <- Rides1617 %>% mutate(Total_DurationDay = (Total_DurationMin <= 24*60))

Day_Length <- nrow(Rides_Day)

sum(Rides_Day$Total_DurationDay/Day_Length)
```
There are 1,498 observations in which ride duration is greater than one day, this accounts for less than 0.02% of our dataset. As our intended outcome of this study is to create a predictive model for daily trips as related to daily weather, we will consider these observations as outliers and remove them.

#Remove outliers from dataset
```{r}
Rides1617_Mod <- Rides1617 %>% filter(Total_DurationMin<=24*60)
```

#2. Correlation testing for the affects of primary weather variables on bikeshare volume:
##- Affect of average temperature
```{r}
# Data subset
Temp <- Rides1617_Mod %>% select(Start_Year:Start_Day, Account_Type, Avg_Temp) %>% group_by(Start_Year, Start_Month, Start_Day, Account_Type, Avg_Temp) %>% tally()  

#Correlation test between daily average temperature and bike count
Cor_Temp <- cor.test(x = Temp$Avg_Temp, y = Temp$n)

Cor_Temp
```
Null hypothesis: the correlation of average daily temperature to daily bike count is 0
Correlation test results show we reject the null hypothesis for 95% confidence in correleation between average daily temperature and bike count

#Plot correlation test results
```{r}
plot_cor_temp <- ggplot(Temp, aes(Avg_Temp, n))
plot_cor_temp + geom_point() + geom_smooth(method="lm") + labs(x = "Avg Temp (F)", y = "Bike Count", title = "Average Daily Temp and Bike Count, 2016-2017 Seasons", subtitle="Pearson's product-moment correlation, p-value < 2.2e-16, corr. coef r = 0.47")
```

##- Affect of average wind speed
```{r}
# Data subset
Wind <- Rides1617_Mod %>% select(Start_Year:Start_Day, Account_Type, Avg_Wind) %>% group_by(Start_Year, Start_Month, Start_Day, Account_Type, Avg_Wind) %>% tally()  

#Correlation test between daily average wind speed and bike count
Cor_Wind <- cor.test(x = Wind$Avg_Wind, y = Wind$n)

Cor_Wind
```
Null hypothesis: the correlation of average daily wind to daily bike count is 0
Correlation test results show we reject the null hypothesis for 95% confidence in a negative correlation between average daily wind speed and bike count

#Plot correlation test results
```{r}
plot_cor_wind <- ggplot(Wind, aes(Avg_Wind, n))
plot_cor_wind + geom_point() + geom_smooth(method="lm") + labs(x = "Avg Wind (mph)", y = "Bike Count", title = "Average Daily Wind Speed and Bike Count, 2016-2017 Seasons", subtitle="Pearson's product-moment correlation, p-value = 3.067e-10, corr. coef r = -0.21")
```

##- Affect of precipitation
```{r}
# Data subset
Precip <- Rides1617_Mod %>% select(Start_Year:Start_Day, Account_Type, Precip) %>% group_by(Start_Year, Start_Month, Start_Day, Account_Type, Precip) %>% tally()  

#Correlation test between daily precipitation and bike count
Cor_Precip <- cor.test(x = Precip$Precip, y = Precip$n)

Cor_Precip
```
Null hypothesis: the correlation of daily precipiration to bike count is 0
Correlation test results show we reject the null hypothesis for 95% confidence in a negative correlation between daily precipitation and bike count.

#Plot correlation test results
```{r}
plot_cor_precip <- ggplot(Precip, aes(Precip, n))
plot_cor_precip + geom_point() + geom_smooth(method="lm") + labs(x = "Precipitation (inches)", y = "Bike Count", title = "Daily Precipitation and Bike Count, 2016-2017 Seasons", subtitle="Pearson's product-moment correlation, p-value = 4.695e-09, corr. coef r = -0.20")
```

- Affect of Relative Humidity
- Affect of Heat Index






















































----
#Multiplot function
```{r include=FALSE}
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```











